# Generated by Django 4.1.5 on 2023-01-03 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vehicle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=250)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_type', models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('gasoline', 'gasoline'), ('battery', 'battery')], default='diesel', max_length=20)),
                ('car_image', models.ImageField(blank=True, null=True, upload_to=vehicle.models.car_image)),
                ('price_per_hour', models.FloatField(default=1.0)),
                ('is_avaliable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentedLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_at', models.DateTimeField()),
                ('rented_duration', models.DateTimeField()),
                ('fine', models.FloatField(default=0.0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter', to=settings.AUTH_USER_MODEL)),
                ('vehicles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicles')),
            ],
        ),
    ]
